<#
Runs the complete local quality gate: compilation, database MCP tests, E2E
helper tests, and an offline smoke test. Any failed stage stops the script and
returns a failing process exit code.
#>

$ErrorActionPreference = "Stop"

# Derive the shared virtual environment and fail early when setup was skipped.
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$WorkspaceRoot = Split-Path -Parent $ProjectRoot
$Python = Join-Path $WorkspaceRoot ".venv\Scripts\python.exe"

if (-not (Test-Path $Python)) {
    throw "Virtual environment missing. Run clean_mcp\scripts\setup.ps1 first."
}

$SystemTemp = [System.IO.Path]::GetFullPath([System.IO.Path]::GetTempPath())
$TestTemp = Join-Path $SystemTemp ("clean-mcp-verify-{0}-{1}" -f $PID, [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $TestTemp -Force | Out-Null

try {
    # Keep generated bytecode and pytest temporary files outside the
    # OneDrive-managed working tree, where editor locks can otherwise interfere.
    $env:PYTHONPYCACHEPREFIX = Join-Path $TestTemp "pycache"
    $PythonFiles = @(& git -C $WorkspaceRoot ls-files "*.py")
    if ($LASTEXITCODE -ne 0 -or $PythonFiles.Count -eq 0) {
        throw "Could not enumerate tracked Python files for compilation."
    }
    $AbsolutePythonFiles = @($PythonFiles | ForEach-Object { Join-Path $WorkspaceRoot $_ })
    & $Python -m py_compile @AbsolutePythonFiles
    if ($LASTEXITCODE -ne 0) { throw "Compilation failed." }

    Push-Location $ProjectRoot
    try {
        & $Python -m pytest -q --basetemp (Join-Path $TestTemp "database-tests")
        if ($LASTEXITCODE -ne 0) { throw "Database MCP test suite failed." }

        # The deterministic demo connector verifies startup without live credentials.
        $env:DB_TYPE = "demo"
        $env:DB_HOST = "demo-local"
        $env:DB_DATABASE = "qa_demo"
        $env:DB_USERNAME = ""
        $env:DB_PASSWORD = ""
        $env:DB_CONNECTION_OPTIONS = "{}"
        $env:DB_ACTIVE_PROFILE = "demo-local"
        & $Python tests\smoke_test.py
        if ($LASTEXITCODE -ne 0) { throw "Smoke test failed." }
    } finally {
        Pop-Location
    }

    Push-Location $WorkspaceRoot
    try {
        & $Python -m pytest -q .\tests -p no:cacheprovider --basetemp (Join-Path $TestTemp "e2e-tests")
        if ($LASTEXITCODE -ne 0) { throw "E2E helper test suite failed." }
    } finally {
        Pop-Location
    }

    Write-Host "All verification gates passed."
} finally {
    $ResolvedTestTemp = [System.IO.Path]::GetFullPath($TestTemp)
    if ((Test-Path -LiteralPath $ResolvedTestTemp) -and $ResolvedTestTemp.StartsWith($SystemTemp, [System.StringComparison]::OrdinalIgnoreCase)) {
        Remove-Item -LiteralPath $ResolvedTestTemp -Recurse -Force -ErrorAction SilentlyContinue
    }
}
